"""Digital Electronics as a v2 concept graph (SITE-V2-DRAFT §10): concepts, flow edges with bridges, relates-to.

Prototype data for v2 session 2. Hand-extracted from the DE knowledge base
(subjects/sem-3/04-digital-electronics/knowledge-base/00-map.md + 01..05). In v2 proper the graph-extraction
step produces this automatically (draft §7); here it is written out so the layout, auto-cutter and layers
can be judged on the real subject.

Flow edges must be acyclic (checked in autocut.py). Leaf / node are never stored: they are derived from degree.
`v1` = id of an existing v1 card (content/01-boolean-kmap.md) whose body the focus prototype renders.
"""

CONCEPTS = []
EDGES = []
RELATES = []


def C(cid, title, kind, topic, unit, gist, v1=None):
    CONCEPTS.append(dict(id=cid, title=title, kind=kind, topic=topic, unit=unit, gist=gist, v1=v1))


def E(a, b, bridge, predict=None):
    EDGES.append(dict(**{"from": a, "to": b}, bridge=bridge, predict=predict))


def R(a, b, note):
    RELATES.append(dict(a=a, b=b, note=note))


# ------------------------------------------------------------------ numbers & codes (assumed prereq, U1 opening)
C("binary", "Binary numbers", "idea", "Numbers & codes", 0, "Place values are powers of 2; n bits give 2ⁿ patterns.")
C("twos-comp", "2's complement", "idea", "Numbers & codes", 0, "Invert and add 1: negative numbers that make subtraction an addition.")
C("bcd", "BCD", "idea", "Numbers & codes", 0, "Each decimal digit in its own 4 bits; 1010–1111 are unused.")
C("gray", "Gray code", "idea", "Numbers & codes", 0, "Neighbouring values differ in exactly one bit.")
C("excess3", "Excess-3", "fact", "Numbers & codes", 0, "BCD + 3. Self-complementing: the 9's complement is just the bits flipped.")
E("binary", "twos-comp", "2's complement is binary on a wheel: n bits count modulo 2ⁿ, so −B is the pattern that brings B back to 0.",
  "If adding B to −B must give 0 in 4 bits, what does −0011 have to be?")
E("binary", "bcd", "BCD reuses 4-bit binary, but only for one decimal digit at a time, so 10 of the 16 patterns are used.")
E("binary", "gray", "Gray code reorders the same 2ⁿ patterns so each step flips one bit instead of possibly many.",
  "Counting 0111 → 1000 in binary flips how many bits at once? Why could that be a problem?")
E("bcd", "excess3", "Add 3 to every BCD digit and the code becomes self-complementing: flipping bits gives the 9's complement.")

# ------------------------------------------------------------------ gates
C("gates", "AND · OR · NOT", "idea", "Gates", 0, "The three primitive operations on 0/1.")
C("truth-table", "Truth table", "idea", "Gates", 0, "Every input combination in binary order: 2ⁿ rows fix the function completely.")
C("xor", "XOR · XNOR", "idea", "Gates", 0, "XOR = 1 when the inputs differ (odd parity); XNOR = equality.")
E("binary", "truth-table", "Rows of a truth table are just the binary numbers 0 … 2ⁿ−1, one per input combination.")
E("gates", "truth-table", "A truth table is the complete behaviour of a gate network, row by row.")
E("gates", "xor", "XOR is built from AND/OR/NOT: A⊕B = A′B + AB′.", "Write A⊕B using only AND, OR, NOT.")
E("truth-table", "xor", "XOR's truth table shows the pattern: 1 exactly on the rows with an odd number of 1s.")

# ------------------------------------------------------------------ boolean algebra
C("bool-laws", "Boolean laws", "idea", "Boolean algebra", 1, "Absorption and the distributive laws collapse expressions on sight.", v1="laws")
C("demorgan", "De Morgan's theorem", "idea", "Boolean algebra", 1, "Complement = flip every literal and swap AND ↔ OR.")
C("consensus", "Consensus theorem", "fact", "Boolean algebra", 1, "AB + A′C + BC = AB + A′C. The BC term is redundant.")
C("minterms", "Minterms & maxterms", "idea", "Boolean algebra", 1, "A minterm is 1 on exactly one row; a maxterm is 0 on exactly one row.")
C("sop-pos", "Σm and ΠM", "idea", "Boolean algebra", 1, "Σm lists the rows where F = 1; ΠM lists the rows where F = 0.", v1="sm-pm")
C("universal", "NAND & NOR are universal", "idea", "Boolean algebra", 1, "Either one alone builds NOT, AND and OR: all of logic.")
C("bubble", "Bubble pushing", "method", "Boolean algebra", 1, "Move inversion bubbles across a gate by swapping its type (De Morgan, drawn).")
C("nand-real", "AND-OR → NAND-NAND", "method", "Boolean algebra", 1, "A two-level SOP becomes all-NAND by adding bubble pairs.")
C("nor-real", "OR-AND → NOR-NOR", "method", "Boolean algebra", 1, "The dual: a two-level POS becomes all-NOR.")
E("gates", "bool-laws", "The laws are the rules gates obey: each one says two gate networks have the same truth table.")
E("bool-laws", "demorgan", "De Morgan is the law that connects complement with AND/OR, which the other laws can't do.")
E("bool-laws", "consensus", "Consensus follows from the laws by expanding BC = BC(A + A′) and absorbing.")
E("truth-table", "minterms", "A minterm is the AND term that is 1 on exactly one row of the truth table.",
  "For inputs A,B,C, which AND term is 1 only on row 101?")
E("minterms", "sop-pos", "OR together the minterms of the 1-rows and you have the function: that list is Σm.")
E("demorgan", "sop-pos", "De Morgan turns the minterm of a row into the maxterm of the same row: Mᵢ = mᵢ′, so ΠM is the other half.")
E("gates", "universal", "Universality asks: can a single gate type rebuild AND, OR and NOT?")
E("demorgan", "universal", "OR from NAND is De Morgan: A + B = (A′·B′)′ = NAND(A′, B′).",
  "Using De Morgan, write A + B with a single NAND and two inverted inputs.")
E("demorgan", "bubble", "A bubble moved across a gate is De Morgan drawn as a picture: AND-with-bubbles = OR.")
E("universal", "bubble", "Bubble pushing is how you make a circuit use only the universal gate.")
E("bubble", "nand-real", "Add a bubble pair on each wire between the AND and OR levels; each AND→NAND and OR→NAND.")
E("sop-pos", "nand-real", "It is the SOP form (AND-then-OR) that maps directly to NAND-NAND.",
  "Which form, SOP or POS, maps straight onto two levels of NAND?")
E("nand-real", "nor-real", "Swap every word in the NAND recipe for its dual: POS, OR-AND, NOR-NOR.")

# ------------------------------------------------------------------ K-maps & minimisation
C("why-min", "Why minimise", "idea", "K-maps", 1, "Same function, fewer literals: less area, power and delay.")
C("kmap-layout", "The K-map", "idea", "K-maps", 1, "A folded truth table in Gray order: neighbours differ in one bit, edges wrap.", v1="kmap-layout")
C("kmap-adj", "Adjacent = XY + XY′ = X", "idea", "K-maps", 1, "Two neighbouring 1-cells merge because the changing variable cancels.")
C("group-size", "Bigger group, fewer letters", "method", "K-maps", 1, "Each doubling of a group deletes one variable.", v1="group-size")
C("group-rules", "What counts as a group", "method", "K-maps", 1, "Power-of-2 rectangles on the wrapped map, as big as possible.", v1="group-rules")
C("pi-epi", "Prime & essential implicants", "idea", "K-maps", 1, "Essentials are forced; then cover the rest with as few as possible.")
C("dont-cares", "Don't-cares", "method", "K-maps", 1, "Use an X only when it makes a group bigger. Otherwise it's 0.", v1="dont-cares")
C("kmap-pos", "Minimal POS: group the 0s", "method", "K-maps", 1, "Group the 0s to get F′, then De Morgan each term.", v1="pos")
C("five-var", "Five variables: two maps", "method", "K-maps", 1, "Same cell on both maps = adjacent. A group across both drops the 5th variable.", v1="five-var")
C("qm", "Quine–McCluskey", "method", "K-maps", 1, "The K-map as a table: combine terms differing in one bit until nothing merges.")
C("kmap-traps", "The five K-map traps", "trap", "K-maps", 1, "Where K-map marks are actually lost.", v1="traps")
E("sop-pos", "why-min", "Σm is correct but huge: one AND gate per minterm. Minimising finds a smaller equivalent.")
E("sop-pos", "kmap-layout", "A K-map is the Σm list drawn as cells: put a 1 in each listed minterm's cell.")
E("gray", "kmap-layout", "The rows and columns go 00, 01, 11, 10 (Gray order), so every step to a neighbour flips one variable.",
  "Why not order the columns 00, 01, 10, 11?")
E("truth-table", "kmap-layout", "Each cell of the map is one row of the truth table, folded into a grid.")
E("why-min", "kmap-layout", "The K-map exists to make minimisation visual.")
E("kmap-layout", "kmap-adj", "Because neighbours differ in one variable, two 1s side by side are XY and XY′.")
E("bool-laws", "kmap-adj", "XY + XY′ = X(Y + Y′) = X: the distributive and complement laws, done with your eyes.",
  "Simplify ABC + ABC′ by algebra. Which variable disappeared?")
E("kmap-adj", "group-size", "Merge two pairs that are themselves adjacent and a second variable cancels: 2ᵏ cells drop k variables.")
E("group-size", "group-rules", "Since only 2ᵏ blocks cancel cleanly, groups must be power-of-2 rectangles, and bigger is always better.")
E("group-rules", "pi-epi", "A group that can't grow is prime. If it's the only one covering some 1, it's essential.")
E("group-rules", "dont-cares", "An X may join a group, so it's there to make groups bigger, never to be covered.")
E("group-rules", "kmap-pos", "The same grouping rules on the 0-cells give F′ in SOP.")
E("demorgan", "kmap-pos", "Complement F′ with De Morgan and each 0-group becomes an OR term of the POS.")
E("group-rules", "five-var", "A 5-variable map is two 4-variable maps stacked; the grouping rules extend across the stack.")
E("pi-epi", "qm", "Quine–McCluskey finds all prime implicants in a table, then picks essentials exactly as on the map.")
E("dont-cares", "qm", "In the table, don't-cares help form bigger implicants but need not be covered.")
E("pi-epi", "kmap-traps", "Most lost marks come from missing an essential group or keeping a redundant one.")
E("dont-cares", "kmap-traps", "Trap: covering an X that didn't need covering, or grouping X's alone.")

# ------------------------------------------------------------------ combinational design (U1)
C("comb-pipeline", "Capture → minimise → realise", "method", "Combinational design", 1, "Every combinational block is designed by the same three steps.")
C("code-conv", "Code converters", "method", "Combinational design", 1, "Binary ↔ Gray and BCD ↔ Excess-3: truth table, K-map, gates.")
C("parity", "Parity generator / checker", "method", "Combinational design", 1, "An XOR tree adds or checks one bit so the count of 1s is even.")
E("pi-epi", "comb-pipeline", "Minimisation (the essential and prime implicants) is the middle step of every design.")
E("nand-real", "comb-pipeline", "Realisation is the last step, usually as NAND-NAND gates.")
E("truth-table", "comb-pipeline", "Capture means writing the truth table from the word problem.")
E("comb-pipeline", "code-conv", "A code converter is the pipeline on a textbook input: code in, code out.")
E("gray", "code-conv", "Binary → Gray comes out as gᵢ = bᵢ ⊕ bᵢ₊₁ once you K-map it.",
  "Which two binary bits decide each Gray bit?")
E("excess3", "code-conv", "BCD → Excess-3 is 'add 3' done as logic, with don't-cares for 1010–1111.")
E("xor", "parity", "XOR is the odd-parity function, so a chain of XORs computes parity of any width.")

# ------------------------------------------------------------------ adders & subtractors (U1)
C("half-adder", "Half adder", "idea", "Adders", 1, "S = A ⊕ B, C = AB.")
C("full-adder", "Full adder", "idea", "Adders", 1, "S = A ⊕ B ⊕ Cin; Cout = AB + Cin(A ⊕ B), the majority function.")
C("fa-from-ha", "Full adder from two half adders", "method", "Adders", 1, "HA(A,B), then HA(sum, Cin), then OR the two carries.")
C("rca", "Ripple-carry adder", "idea", "Adders", 1, "n full adders in a chain; the carry ripples, so delay grows with n.")
C("cla", "Carry look-ahead", "idea", "Adders", 1, "Gᵢ = AᵢBᵢ, Pᵢ = Aᵢ ⊕ Bᵢ: every carry becomes a two-level SOP, delay independent of n.")
C("half-sub", "Half subtractor", "idea", "Adders", 1, "D = A ⊕ B, Borrow = A′B.")
C("full-sub", "Full subtractor", "idea", "Adders", 1, "D = A ⊕ B ⊕ Bin; Bout = A′B + A′Bin + B·Bin.")
C("add-sub", "Adder-subtractor", "method", "Adders", 1, "XOR each B bit with M and feed M as carry-in: one circuit does A + B and A − B.")
C("bcd-adder", "BCD adder", "method", "Adders", 1, "If the sum > 9 or carries out, add 0110.")
C("serial-adder", "Serial adder", "idea", "Adders", 1, "One full adder plus a carry flip-flop, one bit per clock.")
E("xor", "half-adder", "The sum bit of 1+1 is 0 and of 1+0 is 1: that is XOR. The carry is AND.",
  "Add two single bits by hand for all four cases. Which gate gives the sum column?")
E("truth-table", "half-adder", "Write the 4-row table for A + B and read S and C straight off.")
E("half-adder", "full-adder", "A full adder is a half adder that also accepts the carry from the column to its right.")
E("comb-pipeline", "full-adder", "Cout comes from K-mapping the 8-row table: AB + ACin + BCin.")
E("full-adder", "fa-from-ha", "Split the 3-input sum into two 2-input steps: that is two half adders plus an OR.")
E("half-adder", "fa-from-ha", "Each half adder is reused as-is.")
E("full-adder", "rca", "Chain n full adders: each Cout feeds the next Cin, the way you carry in long addition.",
  "In a 4-bit chain, which stage waits longest before its sum is correct?")
E("rca", "cla", "The ripple delay is the problem; look-ahead computes every carry at once from G and P.")
E("sop-pos", "cla", "Unrolling Cᵢ₊₁ = Gᵢ + PᵢCᵢ gives each carry as a two-level SOP, hence constant depth.")
E("half-adder", "half-sub", "Same difference bit (XOR); the borrow is A′B instead of AB.")
E("half-sub", "full-sub", "The same step as HA → FA: accept the borrow from the next column.")
E("full-adder", "full-sub", "Bout has the same shape as Cout with A complemented.")
E("rca", "add-sub", "An adder-subtractor is a ripple adder with a switch on the B input.")
E("twos-comp", "add-sub", "A − B = A + B′ + 1: invert B with XORs and supply the +1 as carry-in.",
  "If M = 1 must mean subtract, what should each B bit be XORed with, and what goes into Cin?")
E("xor", "add-sub", "XOR with M is a controlled inverter: B ⊕ 0 = B, B ⊕ 1 = B′.")
E("rca", "bcd-adder", "The core is a 4-bit binary adder; the rest is correction logic.")
E("bcd", "bcd-adder", "Binary sums above 9 are not BCD, so skip the 6 unused codes by adding 0110.",
  "0111 + 0110 = 1101 in binary. Why is that wrong in BCD, and what fixes it?")
E("full-adder", "serial-adder", "Only one full adder, reused on every clock.")
E("shift-reg", "serial-adder", "Shift registers feed A and B one bit at a time and collect the sum.")
E("d-ff", "serial-adder", "A flip-flop holds the carry between clocks. That makes this adder sequential.")

# ------------------------------------------------------------------ comparators (U2)
C("cmp-1", "1-bit comparator", "idea", "Comparators", 2, "A > B = AB′, A < B = A′B, A = B = XNOR.")
C("cmp-4", "4-bit magnitude comparator", "method", "Comparators", 2, "Compare from the MSB down; the first unequal bit decides.")
E("xor", "cmp-1", "Equality is XNOR; the other two outputs are its AND halves.")
E("truth-table", "cmp-1", "A 4-row table with three outputs.")
E("cmp-1", "cmp-4", "Chain 1-bit results from the MSB: A > B if a higher bit already decided, or if all above are equal and this bit is greater.",
  "For A = 1010, B = 1001, which bit position decides?")
E("comb-pipeline", "cmp-4", "Direct K-mapping of 8 inputs is hopeless, which is why the structured chain is used.")

# ------------------------------------------------------------------ MUX / DEMUX (U2)
C("mux", "Multiplexer", "idea", "MUX / DEMUX", 2, "The select lines choose which input reaches the output: Y = Σ mᵢ·Iᵢ.")
C("mux-fn", "A function on a MUX", "method", "MUX / DEMUX", 2, "Variables on the selects, then each input pin is tied to 0 or 1 from the truth table.")
C("mux-under", "The undersized MUX", "method", "MUX / DEMUX", 2, "n−1 variables on the selects; each input is 0, 1, x or x′.")
C("mux-cascade", "Cascading MUXes", "method", "MUX / DEMUX", 2, "Build a 16:1 from 4:1s in two levels.")
C("demux", "Demultiplexer", "idea", "MUX / DEMUX", 2, "One input routed to one of 2ⁿ outputs.")
E("minterms", "mux", "Each select code is a minterm; the MUX ANDs minterm i with input i.",
  "With selects S1S0 = 10, which input reaches Y, and why is that a minterm?")
E("gates", "mux", "Inside: one AND gate per input and one big OR.")
E("mux", "mux-fn", "Put the variables on the selects and the MUX becomes a truth table with its outputs on the pins.")
E("sop-pos", "mux-fn", "Tie input i to 1 exactly for the minterms in Σm.")
E("mux-fn", "mux-under", "Put one fewer variable on the selects; pair up rows and each pair's output is 0, 1, x or x′.",
  "Rows 6 and 7 differ only in C and give 0, 1. What goes on that input pin?")
E("mux", "mux-cascade", "The first level picks within each group, and a final MUX picks the group.")
E("mux", "demux", "Run the MUX backwards: the selects now choose which output gets the input.")

# ------------------------------------------------------------------ decoder / encoder / display (U2)
C("decoder", "Decoder", "idea", "Decoder / encoder", 2, "n inputs → 2ⁿ outputs, exactly one active: every minterm on its own wire.")
C("dec-fn", "Functions on a decoder", "method", "Decoder / encoder", 2, "OR the decoder outputs for the function's minterms.")
C("dec-expand", "Decoder expansion", "method", "Decoder / encoder", 2, "Two 3:8s plus an enable make a 4:16.")
C("encoder", "Encoder", "idea", "Decoder / encoder", 2, "The inverse: one active input out of 2ⁿ → its n-bit code.")
C("prio-enc", "Priority encoder", "idea", "Decoder / encoder", 2, "If several inputs are active, the highest one wins, plus a 'valid' output.")
C("seven-seg", "BCD → 7-segment", "method", "Display", 2, "Seven K-maps, one per segment, with 1010–1111 as don't-cares.")
C("ca-cc", "Common anode vs common cathode", "trap", "Display", 2, "Common anode lights on 0. Get it wrong and every segment is inverted.")
C("mux-display", "Multiplexed display", "idea", "Display", 2, "Light one digit at a time, fast; your eye sees them all.")
E("minterms", "decoder", "A decoder produces all 2ⁿ minterms at once, each on its own output.")
E("decoder", "dec-fn", "Since every minterm is available, a function is an OR of the right outputs.")
E("sop-pos", "dec-fn", "The OR gate's inputs are exactly the Σm list.",
  "F = Σm(1, 4, 6). Which decoder outputs go into the OR?")
E("decoder", "dec-expand", "The top input bit becomes the enable that chooses which decoder is active.")
E("decoder", "encoder", "Reverse the direction: one active line in, its binary code out.")
E("encoder", "prio-enc", "A plain encoder breaks if two inputs are active; priority fixes it by letting the highest win.")
E("dont-cares", "prio-enc", "The table is full of X's: once a higher input is 1, the lower ones don't matter.")
E("bcd", "seven-seg", "The input is a BCD digit, so 1010–1111 never occur.")
E("dont-cares", "seven-seg", "Those six unused codes are don't-cares on every segment map.")
E("comb-pipeline", "seven-seg", "Seven outputs, so the pipeline runs seven times.")
E("seven-seg", "ca-cc", "The same decoder logic drives either display type, but the active level flips.")
E("seven-seg", "mux-display", "One segment decoder is shared across all digits by switching which digit is on.")
E("decoder", "mux-display", "A decoder picks which digit's common pin is enabled.")

# ------------------------------------------------------------------ shifter / ALU (U2)
C("barrel", "Barrel shifter", "idea", "Shifter / ALU", 2, "Shift by any amount in one step: log₂n levels of MUXes.")
C("alu", "ALU", "idea", "Shifter / ALU", 2, "An adder, a logic unit and a MUX; the opcode selects the result.")
C("alu-74181", "74181 function table", "fact", "Shifter / ALU", 2, "The classic 4-bit ALU chip: 16 logic and 16 arithmetic operations.")
E("mux", "barrel", "Each output bit is a MUX choosing among the input bits; stages shift by 1, 2, 4, …",
  "To shift an 8-bit word by 0–7 places, how many MUX stages do you need?")
E("add-sub", "alu", "The arithmetic half of an ALU is the adder-subtractor.")
E("mux", "alu", "A final MUX, driven by the opcode, picks which unit's result comes out.")
E("alu", "alu-74181", "The 74181 is the textbook example of an ALU chip.")

# ------------------------------------------------------------------ memory boundary + latches (U3)
C("memory-line", "Combinational vs sequential", "idea", "Latches", 3, "Feedback makes the output depend on the past: the circuit remembers.")
C("sr-latch", "SR latch", "idea", "Latches", 3, "Two cross-coupled NORs: set, reset, hold. S = R = 1 is forbidden.")
C("gated-latch", "Gated latch", "idea", "Latches", 3, "Add an enable: follows its inputs while EN = 1, holds while EN = 0.")
C("d-latch", "D latch", "idea", "Latches", 3, "S = D, R = D′: the forbidden state is impossible. Transparent while enabled.")
E("comb-pipeline", "memory-line", "Everything so far is a pure function of the present inputs. Add feedback and that stops being true.",
  "Wire an OR gate's output back into one of its own inputs. Once the output is 1, can it ever go back to 0?")
E("memory-line", "sr-latch", "The smallest circuit with feedback that holds a bit: two gates feeding each other.")
E("universal", "sr-latch", "It is built from NOR or NAND, the universal gates.")
E("sr-latch", "gated-latch", "Put AND gates in front so that S and R only reach the latch while enabled.")
E("gated-latch", "d-latch", "Drive S and R from one input and its complement, and S = R = 1 can never happen.")

# ------------------------------------------------------------------ flip-flops (U3)
C("edge", "Edge triggering", "idea", "Flip-flops", 3, "Sample only at the clock edge, not while the clock is high.")
C("ff-types", "SR · D · JK · T flip-flops", "idea", "Flip-flops", 3, "Four input conventions around the same one-bit store.")
C("d-ff", "D flip-flop", "idea", "Flip-flops", 3, "Q⁺ = D at the edge: the plain one-bit register.")
C("char-eq", "Characteristic equations", "method", "Flip-flops", 3, "Q⁺ = D, JQ′ + K′Q, T ⊕ Q, S + R′Q.")
C("excitation", "Excitation tables", "method", "Flip-flops", 3, "Given Q → Q⁺, which inputs are needed? JK is full of X's.")
C("ff-conv", "Flip-flop conversion", "method", "Flip-flops", 3, "The wanted type's needs, the existing type's excitation table, then a K-map.")
C("race", "Race-around", "trap", "Flip-flops", 3, "A level-triggered JK with J = K = 1 toggles over and over while the clock is high.")
C("master-slave", "Master–slave JK", "idea", "Flip-flops", 3, "Two latches on opposite clock phases: at most one toggle per clock.")
C("async-in", "Preset & clear", "idea", "Flip-flops", 3, "Direct inputs that force Q regardless of the clock.")
C("waveform", "Drawing a timing waveform", "method", "Flip-flops", 3, "Mark each active edge, read the inputs there, and hold Q between edges.")
E("d-latch", "edge", "A latch is transparent the whole time EN is high, so changes race through. An edge narrows the window to an instant.",
  "If D changes twice while EN is high, how many times does a D latch's Q change?")
E("edge", "d-ff", "A D latch made edge-triggered is the D flip-flop.")
E("d-latch", "d-ff", "The same Q⁺ = D rule, now applied only at the edge.")
E("d-ff", "ff-types", "D is the simplest; SR, JK and T are the same store with different input rules.")
E("sr-latch", "ff-types", "SR and JK inherit the set/reset idea; JK turns the forbidden 11 into toggle.")
E("ff-types", "char-eq", "Each type's behaviour, written as one Boolean equation for Q⁺.")
E("bool-laws", "char-eq", "The equations are derived from each type's truth table by algebra or K-map.")
E("char-eq", "excitation", "Turn the equation around: for each wanted transition, which inputs produce it?",
  "A JK flip-flop has Q = 0 and you want Q⁺ = 1. Does K matter?")
E("dont-cares", "excitation", "Inputs that don't matter for a transition become X's, which later help the K-maps.")
E("excitation", "ff-conv", "The wanted type's input needs, looked up in the existing type's excitation table.")
E("group-rules", "ff-conv", "Then K-map each input of the flip-flop you actually have.")
E("ff-types", "race", "JK's toggle (J = K = 1) is the case that goes wrong under level triggering.")
E("gated-latch", "race", "The cause is transparency: the output feeds back while the clock is still high.")
E("race", "master-slave", "Split the flip-flop into two latches that are never transparent at the same time.",
  "If the master only listens while CLK = 1 and the slave only while CLK = 0, how many times can Q change per clock?")
E("ff-types", "async-in", "Every flip-flop type gets two extra pins that bypass the clock for initialisation.")
E("ff-types", "waveform", "You need each type's rule to know what Q does at an edge.")
E("edge", "waveform", "Only the edges matter; between them Q is flat.")

# ------------------------------------------------------------------ counters (U3)
C("ripple-counter", "Ripple counter", "idea", "Counters", 3, "Each flip-flop clocks the next: simple, but delays add and the count glitches.")
C("ff-count", "How many flip-flops", "fact", "Counters", 3, "The smallest n with 2ⁿ ≥ N.")
C("mod-n-clear", "Mod-N by clearing", "method", "Counters", 3, "Detect N and fire CLEAR: mod-10 clears at 1010.")
C("sync-counter", "Synchronous counter design", "method", "Counters", 3, "State table → excitation table → K-map each input. The highest-value exam question.")
C("self-start", "Self-starting check", "method", "Counters", 3, "Trace every unused state: does it fall back into the cycle?")
E("ff-types", "ripple-counter", "A T flip-flop with T = 1 halves its clock; chain them and you count.",
  "A toggling flip-flop is clocked by a 1 kHz square wave. What frequency comes out of Q?")
E("binary", "ff-count", "n flip-flops hold 2ⁿ states, so a mod-N counter needs n with 2ⁿ ≥ N.")
E("ripple-counter", "ff-count", "Counter size is the first design decision.")
E("ripple-counter", "mod-n-clear", "To stop a ripple counter at N, reset it the moment N appears.")
E("async-in", "mod-n-clear", "The reset uses the asynchronous CLEAR pin, which is also why a brief glitch state appears.")
E("excitation", "sync-counter", "For each present → next state, the excitation table gives every flip-flop's inputs.")
E("group-rules", "sync-counter", "Each flip-flop input is then a K-map over the present-state bits.")
E("ripple-counter", "sync-counter", "The motivation is ripple's accumulated delay: one shared clock removes it.")
E("sync-counter", "self-start", "Unused states are don't-cares in the design, so check where the logic sends them.")

# ------------------------------------------------------------------ shift registers (U3)
C("shift-reg", "Shift registers", "idea", "Shift registers", 3, "A chain of D flip-flops on one clock: SISO, SIPO, PISO, PIPO.")
C("universal-sr", "Universal shift register", "idea", "Shift registers", 3, "The 74194: a MUX in front of each flip-flop picks hold, left, right or load.")
C("ring", "Ring counter", "idea", "Shift registers", 3, "Feed the last Q back to the first: a single 1 circulates, n states.")
C("johnson", "Johnson counter", "idea", "Shift registers", 3, "Feed back the complement: 2n states from n flip-flops.")
E("d-ff", "shift-reg", "Each D flip-flop passes its bit to the next on every clock.")
E("shift-reg", "universal-sr", "Add a choice at each input: keep, take from the left, take from the right, or load.")
E("mux", "universal-sr", "That choice is a 4:1 MUX per bit, with the mode lines as selects.")
E("shift-reg", "ring", "Close the loop and the pattern circulates forever.")
E("ring", "johnson", "Invert the feedback and the pattern fills with 1s, then empties: twice the states.",
  "A 3-bit ring counter has 3 states. How many does a 3-bit Johnson counter have?")

# ------------------------------------------------------------------ timing (U3/U4)
C("tpd", "Propagation delay", "idea", "Timing", 3, "Outputs change a few ns after inputs, never instantly.")
C("setup-hold", "Setup & hold", "idea", "Timing", 3, "The input must be still for t_su before and t_h after the edge.")
C("fmax", "Maximum clock frequency", "method", "Timing", 3, "f_max = 1 / (t_pd,FF + t_comb,max + t_su).")
C("hold-check", "Hold check", "method", "Timing", 3, "Shortest path: t_pd,FF + t_comb,min ≥ t_h.")
C("metastab", "Metastability", "idea", "Timing", 3, "Violate setup or hold and Q can hang between 0 and 1.")
C("skew", "Clock skew", "idea", "Timing", 4, "The clock reaches flip-flops at different times, eating setup or hold margin.")
C("hazards", "Hazards & glitches", "idea", "Timing", 4, "Unequal path delays make a brief wrong output. The consensus term covers the gap.")
E("gates", "tpd", "Real gates take time to switch.")
E("edge", "setup-hold", "The edge is not a mathematical instant; the flip-flop needs a still input around it.")
E("tpd", "setup-hold", "Setup time exists because the flip-flop's internal gates have delay too.")
E("setup-hold", "fmax", "The next edge may not arrive until the slowest path settles plus t_su.",
  "t_pd,FF = 8 ns, t_comb = 12 ns, t_su = 3 ns. What is the shortest clock period?")
E("tpd", "fmax", "Every term in the sum is a delay.")
E("setup-hold", "hold-check", "Hold is the opposite race: the new value must not arrive too fast.")
E("setup-hold", "metastab", "When the rules are broken, the bistable can balance on its hump.")
E("fmax", "skew", "Skew is added to one side of the timing budget.")
E("hold-check", "skew", "... and taken from the other.")
E("tpd", "hazards", "Two paths with different delays briefly disagree.")
E("consensus", "hazards", "Adding the redundant consensus term keeps the output 1 across the transition.",
  "AB + A′C glitches when A switches with B = C = 1. Which extra term covers that step?")

# ------------------------------------------------------------------ state machines (U4)
C("fsm", "The FSM model", "idea", "State machines", 4, "State register + next-state logic + output logic. Every sequential machine fits.")
C("moore-mealy", "Moore vs Mealy", "idea", "State machines", 4, "Moore: output from the state only. Mealy: from the state and the input.")
C("state-diag", "State diagram → state table", "method", "State machines", 4, "Circles and arrows, rewritten as a present → next table.")
C("fsm-pipeline", "The FSM design pipeline", "method", "State machines", 4, "Diagram → table → reduce → assign → excitation → K-maps.")
C("state-red", "State reduction", "method", "State machines", 4, "Merge states with the same outputs and the same next states.")
C("state-assign", "State assignment", "idea", "State machines", 4, "Binary, Gray or one-hot codes: the choice changes the logic's cost.")
C("seq-det", "Sequence detector", "method", "State machines", 4, "Detect 1011 in a bit stream. The classic FSM exam question.")
C("asm", "ASM charts", "idea", "State machines", 4, "A flowchart form of the same machine.")
C("prbs", "PRBS generator", "idea", "State machines", 4, "A shift register with XOR feedback: a long pseudo-random sequence.")
C("pulse-train", "Pulse-train generator", "method", "State machines", 4, "A counter plus decoding makes any repeating pattern.")
C("clock-gen", "Clock generation", "idea", "State machines", 4, "555 astable, ring oscillator, crystal: where the clock comes from.")
C("async-fsm", "Asynchronous circuits", "idea", "State machines", 4, "Sequential logic with no clock: hazards and races become the whole problem.")
E("memory-line", "fsm", "Every circuit with memory is a state machine: stored state plus combinational logic around it.")
E("d-ff", "fsm", "The state register is a row of D flip-flops.")
E("comb-pipeline", "fsm", "Next-state and output logic are ordinary combinational blocks.")
E("fsm", "moore-mealy", "The two variants differ in what the output logic is allowed to look at.",
  "A Mealy output can change without a clock edge. Why?")
E("moore-mealy", "state-diag", "Moore puts outputs in the circles; Mealy puts them on the arrows.")
E("state-diag", "fsm-pipeline", "The table is the input to the synthesis pipeline.")
E("sync-counter", "fsm-pipeline", "A synchronous counter is the pipeline with no inputs: you have already done it once.")
E("excitation", "fsm-pipeline", "Same step as for counters: the excitation table gives each flip-flop's inputs.")
E("state-diag", "state-red", "Equivalent states show up as identical rows of the table.")
E("fsm-pipeline", "state-assign", "The codes you choose decide how big the K-maps' results are.")
E("fsm-pipeline", "seq-det", "Run the full pipeline on a word problem.")
E("state-red", "seq-det", "Detector diagrams usually have redundant states to merge.")
E("state-diag", "asm", "The same information, drawn as a flowchart with decision boxes.")
E("shift-reg", "prbs", "The register holds the state and shifts every clock.")
E("xor", "prbs", "XOR of chosen taps is fed back. With the right taps you get 2ⁿ − 1 states before repeating.")
E("sync-counter", "pulse-train", "Count, then decode the count into the pattern you want.")
E("tpd", "clock-gen", "A ring oscillator's frequency is set by gate delay: f = 1 / (2N·t_pd).")
E("hazards", "async-fsm", "Without a clock to wait things out, every glitch is a possible wrong state.")
E("fsm", "async-fsm", "The same model with the clock removed.")

# ------------------------------------------------------------------ logic families (U5)
C("yardsticks", "V_OH · V_OL · V_IH · V_IL", "idea", "Logic families", 5, "The voltages that count as a guaranteed 0 or 1.")
C("noise-margin", "Noise margin", "method", "Logic families", 5, "NM_H = V_OH − V_IH, NM_L = V_IL − V_OL. Standard TTL: 0.4 V each.")
C("fanout", "Fan-out", "method", "Logic families", 5, "How many inputs one output can drive: standard TTL = 10.")
C("pdp", "Power–delay product", "fact", "Logic families", 5, "Power × t_pd: energy per switch, the family's figure of merit.")
C("ttl-nand", "TTL NAND gate", "idea", "Logic families", 5, "The 7400: multi-emitter input, totem-pole output.")
C("totem", "Totem pole vs open collector", "idea", "Logic families", 5, "Active pull-up is fast; open collector allows wired-AND.")
C("tristate", "Tristate output", "idea", "Logic families", 5, "0, 1 or disconnected: how many drivers share one bus.")
C("ecl", "ECL", "idea", "Logic families", 5, "Non-saturating differential pair: fastest, most power-hungry.")
C("cmos-inv", "CMOS inverter", "idea", "Logic families", 5, "pMOS up, nMOS down: almost no static power.")
C("cmos-gates", "CMOS NAND / NOR", "idea", "Logic families", 5, "Series nMOS with parallel pMOS: the dual networks are De Morgan in silicon.")
C("interfacing", "TTL ↔ CMOS interfacing", "method", "Logic families", 5, "Check that one family's outputs meet the other's input levels; add a pull-up if not.")
E("gates", "yardsticks", "A real gate's 0 and 1 are voltage ranges, not points.")
E("yardsticks", "noise-margin", "The gap between what an output guarantees and what an input needs.",
  "V_OH = 2.4 V and V_IH = 2.0 V. How much noise can a high signal tolerate?")
E("yardsticks", "fanout", "Each input draws current; the output's current limit sets how many inputs it can drive.")
E("tpd", "pdp", "Delay is one factor of the product.")
E("universal", "ttl-nand", "NAND is the family's basic cell because it is universal.")
E("noise-margin", "ttl-nand", "A family is described by its NAND's noise margin, ...")
E("fanout", "ttl-nand", "... its fan-out, delay and power.")
E("ttl-nand", "totem", "The totem-pole output stage, and what happens if you replace it.")
E("totem", "tristate", "Add a disable that switches off both output transistors.")
E("ttl-nand", "ecl", "ECL avoids saturation, which is TTL's speed limit.")
E("pdp", "ecl", "It buys speed with power: a high power-delay product.")
E("yardsticks", "cmos-inv", "CMOS swings rail to rail: the widest levels of any family.")
E("cmos-inv", "cmos-gates", "Stack the transistors: series in one network, parallel in the other.")
E("demorgan", "cmos-gates", "The pull-up network is the De Morgan dual of the pull-down.",
  "The nMOS pull-down of a NAND is two in series. What must the pMOS pull-up be?")
E("ttl-nand", "interfacing", "Its output levels, ...")
E("cmos-inv", "interfacing", "... this one's input levels.")
E("noise-margin", "interfacing", "Interfacing is a noise-margin check across two families.")

# ------------------------------------------------------------------ memories & PLDs (U5)
C("memory-org", "Memory: address → word", "idea", "Memories & PLDs", 5, "A decoder picks one row of storage cells.")
C("rom", "ROM as a truth table", "idea", "Memories & PLDs", 5, "The address is the input, the word is the output: any function.")
C("sram-dram", "SRAM vs DRAM", "idea", "Memories & PLDs", 5, "A latch cell vs a capacitor cell: fast and big vs dense and refreshed.")
C("pld", "PROM · PLA · PAL", "idea", "Memories & PLDs", 5, "Programmable AND and OR planes: which plane is fixed?")
C("pld-impl", "Implementing logic on a PLA", "method", "Memories & PLDs", 5, "Minimise, share product terms, fill the programming table.")
E("decoder", "memory-org", "The address decoder enables exactly one word line.",
  "A memory has 10 address bits. How many word lines does the decoder drive?")
E("d-latch", "memory-org", "Each bit of storage is a latch-like cell.")
E("memory-org", "rom", "Make the cells fixed and memory becomes a lookup table.")
E("minterms", "rom", "Each address is a minterm and each stored word is that row's output: a ROM is a truth table in silicon.")
E("memory-org", "sram-dram", "Two ways to build the cell.")
E("sr-latch", "sram-dram", "The SRAM cell is a cross-coupled latch (two inverters).")
E("cmos-inv", "sram-dram", "... built from CMOS inverters, six transistors in all.")
E("rom", "pld", "A PROM is a ROM: a fixed AND plane (a decoder) with a programmable OR plane.")
E("sop-pos", "pld", "Every PLD is an AND plane feeding an OR plane: SOP in hardware.")
E("pld", "pld-impl", "Filling a PLA's programming table.")
E("pi-epi", "pld-impl", "The PLA has a limited number of product terms, so minimise and share them.")

# ------------------------------------------------------------------ relates-to (web layer, never on the map)
R("mux", "decoder", "Both generate minterms: a MUX ANDs each one with an input, a decoder puts each on a wire.")
R("demux", "decoder", "A demux is a decoder whose enable carries the data.")
R("rca", "ripple-counter", "The same disease: each stage waits on the previous one, so delay grows with n.")
R("cla", "sync-counter", "The same cure: compute everything in parallel instead of in a chain.")
R("johnson", "gray", "The Johnson sequence changes one bit per step, like Gray code.")
R("ring", "state-assign", "A ring counter is one-hot state assignment.")
R("hazards", "gray", "Unit-distance changes are why Gray-coded signals don't glitch.")
R("metastab", "sr-latch", "Metastability is the SR latch's forbidden state in time: balanced between two wells.")
R("rom", "mux-fn", "Both implement a function straight from its truth table, no minimising.")
R("parity", "prbs", "Both are XOR trees: one checks, one generates.")
R("tristate", "mux", "A tristate bus is a distributed MUX: one enabled driver at a time.")
R("barrel", "shift-reg", "Shifting in one step (combinational) vs one bit per clock (sequential).")
R("alu", "cla", "Real ALUs use look-ahead for their adder.")
R("cmos-gates", "universal", "In CMOS, NAND is the cheapest gate, so universality is also the economical choice.")
R("serial-adder", "memory-line", "The serial adder is the first sequential circuit you meet.")
R("master-slave", "shift-reg", "Master–slave is a two-stage shift register inside one flip-flop.")
R("pld", "nand-real", "Two-level AND-OR, again: PLDs are the NAND-NAND form made programmable.")
R("excess3", "twos-comp", "Both make complementing easy so that subtraction becomes addition.")
